# Generated by Django 5.2.6 on 2025-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.IntegerField(choices=[(1, 'Sport'), (2, 'Mountain'), (3, 'Town'), (4, 'Light')], default=4)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1024)),
                ('price', models.IntegerField(default=None, max_length=6)),
                ('is_there_any', models.BooleanField(default=False)),
                ('bike_amount', models.IntegerField()),
            ],
        ),
    ]
